In [5]:
import pickle
import numpy as np
from transformers import *
from image_helper import * 

with open('./data/southwest_images_new_train.pkl', 'rb') as train_f:
    saved_southwest_dataset_train = pickle.load(train_f)
    print(saved_southwest_dataset_train)
with open('./data/southwest_images_new_test.pkl', 'rb') as test_f:
    saved_southwest_dataset_test = pickle.load(test_f)

print('shape of edge case train data (southwest airplane dataset train)',saved_southwest_dataset_train.shape)
print('shape of edge case test data (southwest airplane dataset test)',saved_southwest_dataset_test.shape)

# np.ones((x,y), dype=int) 建立一个[x,y]维的int型数组，且值为1，再*9
sampled_targets_array_train = 9 * np.ones((saved_southwest_dataset_train.shape[0],), dtype =int)
print(sampled_targets_array_train)
sampled_targets_array_test = 9 * np.ones((saved_southwest_dataset_test.shape[0],), dtype =int)
print(np.max(saved_southwest_dataset_train))

transform = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
        ])

trainset = Customize_Dataset(X=saved_southwest_dataset_train, Y=sampled_targets_array_train, transform=transform)
poisoned_train_loader = DataLoader(dataset = trainset, batch_size = 64, shuffle = True, num_workers=1)
print(trainset)

testset = Customize_Dataset(X=saved_southwest_dataset_test, Y=sampled_targets_array_test, transform=transform)
poisoned_test_loader = DataLoader(dataset = testset, batch_size = 64, shuffle = True, num_workers=1)


[[[[217 229 241]
   [222 233 244]
   [227 236 245]
   ...
   [212 225 239]
   [204 220 236]
   [196 214 231]]

  [[223 234 243]
   [228 236 246]
   [231 238 247]
   ...
   [216 228 240]
   [210 223 237]
   [202 218 233]]

  [[227 236 244]
   [230 238 247]
   [234 240 248]
   ...
   [219 230 241]
   [214 226 238]
   [208 221 233]]

  ...

  [[213 205 200]
   [216 208 203]
   [217 209 203]
   ...
   [206 195 190]
   [196 187 181]
   [185 175 170]]

  [[201 192 187]
   [206 196 191]
   [208 198 193]
   ...
   [205 197 191]
   [197 188 183]
   [186 177 172]]

  [[197 187 182]
   [201 190 184]
   [204 193 187]
   ...
   [205 197 191]
   [197 188 183]
   [184 175 170]]]


 [[[196 214 231]
   [202 218 233]
   [208 221 233]
   ...
   [185 175 170]
   [186 177 172]
   [184 175 170]]

  [[204 220 236]
   [210 223 237]
   [214 226 238]
   ...
   [196 187 181]
   [197 188 183]
   [197 188 183]]

  [[212 225 239]
   [216 228 240]
   [219 230 241]
   ...
   [206 195 190]
   [205 197 191]
   [205 197